# configmap.yaml
agent:
  configMap:
    create: true
    content: |
      logging {
      	level  = "info"
      	format = "logfmt"
      }

      discovery.kubernetes "pods" {
      	role = "pod"
      }

      discovery.kubernetes "nodes" {
      	role = "node"
      }

      discovery.kubernetes "services" {
      	role = "service"
      }

      discovery.kubernetes "endpoints" {
      	role = "endpoints"
      }

      discovery.kubernetes "endpointslices" {
      	role = "endpointslice"
      }

      discovery.kubernetes "ingresses" {
      	role = "ingress"
      }
      
      prometheus.scrape "pods" {
        targets    = discovery.kubernetes.pods.targets
        forward_to = [prometheus.remote_write.default.receiver]
      }
      
      prometheus.scrape "nodes" {
          targets    = discovery.kubernetes.nodes.targets
          forward_to = [prometheus.remote_write.default.receiver]
      }

      prometheus.remote_write "default" {
        endpoint {
          url = "http://prometheus-stack-prometheus.prometheus:9090/api/v1/write"
        }
      }