fullnameOverride: loki

customParams:
  authEnabled: true

serviceMonitor:
  enabled: true

prometheusRule:
  enabled: true

ingester:
  kind: StatefulSet
  replicas: 1
  autoscaling:
    enabled: false
  resources: {}

distributor:
  replicas: 1
  autoscaling:
    enabled: false
  resources: {}

querier:
  replicas: 1
  autoscaling:
    enabled: false
  resources: {}

queryFrontend:
  replicas: 1
  autoscaling:
    enabled: false
  resources: {}

queryScheduler:
  enabled: true
  replicas: 2
  affinity: ''
  resources: {}

gateway:
  enabled: true
  replicas: 1
  autoscaling:
    enabled: false
  resources: {}

  basicAuth:
    enabled: true
    username: log-user
    password: log-password

compactor:
  enabled: true
  resources: {}

memcachedExporter:
  enabled: true

memcachedChunks:
  enabled: true
  replicas: 1
  resources: {}

memcachedFrontend:
  enabled: true
  replicas: 1
  resources: {}

# TSDB not required
memcachedIndexQueries:
  enabled: false
  replicas: 1
  resources: {}

# TSDB not required
memcachedIndexWrites:
  enabled: false
  resources: {}
