apiVersion: v1
kind: ConfigMap
metadata:
  name: beyla-config
data:
  beyla-config.yml: |
    print_traces: true
    log_level: debug
    otel_traces_export:
      endpoint: http://tempo-distributor.tracing:4317
    prometheus_export:
      port: 8999
      path: /metrics
      report_target: false
      report_peer: false
    internal_metrics:
      port: 8990
      path: /metrics
    open_port: 80-8999
    #executable_name: "goblog"
#    attributes:
#      kubernetes:
#        enable: true
#    routes:
#      patterns:
#        - /*
      #    discovery:
#      services:
#        - namespace: default
#          exe_path_regexp: node