# daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: beyla
  labels:
      app: beyla
      instrumentation: beyla
spec:
  selector:
    matchLabels:
      instrumentation: beyla
  template:
    metadata:
      labels:
        instrumentation: beyla
    spec:
      serviceAccountName: default
      hostPID: true # important!
      # mount the ConfigMap as a folder
      volumes:
        - name: beyla-config
          configMap:
            name: beyla-config
      containers:
        - name: beyla
          image: grafana/beyla:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true # important!
          command: ["/beyla", "--config=/config/beyla-config.yml"]
          ports:
            # expose the metrics ports
            - containerPort: 8999
              name: metrics
            - containerPort: 8990
              name: internal
          volumeMounts:
            - mountPath: /config
              name: beyla-config