apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: beyla
  labels:
      app: beyla
      instrumentation: beyla
spec:
  selector:
    matchLabels:
      instrumentation: beyla
  template:
    metadata:
      labels:
        instrumentation: beyla
    spec:
      serviceAccountName: default
      hostPID: true  #important!
      containers:
        - name: beyla
          image: grafana/beyla:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command: ["/beyla", "--config=/config/beyla-config.yml"]
          ports:
            - containerPort: 8999
              name: metrics
            - containerPort: 8990
              name: internal
          # mount the previous ConfigMap as a folder
          volumeMounts:
            - mountPath: /config
              name: beyla-config
      # tell beyla where to find the configuration file
      volumes:
        - name: beyla-config
          configMap:
            name: beyla-config