apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: beyla-podmonitor
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      instrumentation: beyla
  podMetricsEndpoints:
    - port: metrics
