# values.yaml
fullnameOverride: loki

customParams:
  authEnabled: false

serviceMonitor:
  enabled: false

prometheusRule:
  enabled: false

ingester:
  kind: StatefulSet
  replicas: 1
  autoscaling:
    enabled: false
  resources: {}

distributor:
  replicas: 1
  autoscaling:
    enabled: false
  resources: {}

querier:
  replicas: 1
  autoscaling:
    enabled: false
  resources: {}

queryFrontend:
  replicas: 1
  autoscaling:
    enabled: false
  resources: {}

queryScheduler:
  enabled: false
  replicas: 2
  affinity: ''
  resources: {}

gateway:
  enabled: true
  replicas: 1
  autoscaling:
    enabled: false
  resources: {}

compactor:
  enabled: false
  resources: {}